# Cloud Run configuration
runtime: nodejs18

# Environment variables
env_variables:
  NODE_ENV: production
  PORT: 8080
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Resources
resources:
  cpu: 1
  memory_gb: 2

# Health check
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 3
  healthy_threshold: 2

# Network
network:
  forwarded_ports:
    - 8080

# Service configuration
service: fdot-plan-generator
